using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using static Demo_Project.SceneManager;

    public class Enemy_Boss2_Pattern1_Projectile01 : MonoBehaviour
    {
        [Header("Ïù¥ÌéôÌä∏ ÌîÑÎ¶¨Ìåπ")]
        public GameObject impactObject = null;
        public GameObject muzzleFlashEffect = null;

        
        [Header("Ï¥ùÏïå Í¥ÄÎ†® ÏÑ§Ï†ï")]
        [SerializeField] private float bulletSpeed = 5f;
        [SerializeField] private float bulletDamage = 10f;
        [SerializeField] private float impactEffectLifeTime = 0.5f;
        
        [Header("ÌöåÏ†Ñ Í¥ÄÎ†®")]
        [SerializeField] private float moveAngleRad = 0; // ÎùºÎîîÏïà
        [SerializeField] private float spriteAngleRad = 0; // ÎùºÎîîÏïà
        
        [Header("ÏÑ§Ï†ï")]
        public string targetTag = "Player";
        public bool rotateSprite = true;
        public bool muzzleFlash = true;
        public float rotationSpeed = 0;
        public float rotationRange = 0;

        private bool rotateClockwise = false;
        private float timeSinceLastFrame = 0;
        
        private bool isFacingLeft = false;
        
        public void SetFacingDirection(bool facingLeft)
        {
            isFacingLeft = facingLeft;
        }

        void Start()
        {
            
            if (rotateSprite)
            {
                transform.rotation = Quaternion.Euler(0, 0, spriteAngleRad * Mathf.Rad2Deg);
            }

            if (muzzleFlash && muzzleFlashEffect != null)
            {
                GameObject flash = Instantiate(muzzleFlashEffect, transform.position, Quaternion.identity);

                // ZÏ∂ï ÌöåÏ†ÑÏúºÎ°ú ÌååÌã∞ÌÅ¥ Î∞©Ìñ• Ï°∞Ï†ï
                float rotZ = isFacingLeft ? 180f : 0f;
                flash.transform.rotation = Quaternion.Euler(0, 0, rotZ);

                Destroy(flash, 0.5f);
            }
        }

        void Update()
        {
            timeSinceLastFrame = Time.deltaTime / 0.001666f;
            Move();
            RotateProjectile();
        }

        public void Init(float damage, float speed, float angle)
        {
            bulletDamage = damage;
            bulletSpeed = speed;
            moveAngleRad = angle;
            spriteAngleRad = angle;
        }

        void Move()
        {
            float tempMoveSpeed = (bulletSpeed * timeSinceLastFrame) / 100f;
            Vector3 direction = new Vector3(Mathf.Cos(moveAngleRad), Mathf.Sin(moveAngleRad), 0);
            transform.Translate(direction * tempMoveSpeed, Space.World);
        }

        void RotateProjectile()
        {
            if (rotationRange > 0 && rotationSpeed > 0)
            {
                float zRot = rotationSpeed * timeSinceLastFrame;
                if (!rotateClockwise)
                {
                    transform.Rotate(0, 0, zRot);
                    if (transform.rotation.z * Mathf.Rad2Deg >= rotationRange)
                        rotateClockwise = true;
                }
                else
                {
                    transform.Rotate(0, 0, -zRot);
                    if (transform.rotation.z * Mathf.Rad2Deg <= -rotationRange)
                        rotateClockwise = false;
                }
            }
        }

        
        void OnTriggerEnter2D(Collider2D col)
        {
            if (!col.CompareTag(targetTag)) return;

            Player player = col.GetComponent<Player>();
            if (player != null)
            {
                player.TakeDamage(bulletDamage);
            }

            Impact();
        }

        void Impact()
        {
            if (impactObject != null)
            {
                GameObject impact = Instantiate(impactObject, transform.position, Quaternion.identity);
                Destroy(impact, impactEffectLifeTime); // üî• impact Ïù¥ÌéôÌä∏ Ï†úÍ±∞
            }

            Destroy(gameObject);
        }
    }